apiVersion: v1
kind: Service
metadata:
  labels:
    app: MeetingMgtsrv
    service: MeetingMgtsrv
  name: MeetingMgtsrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: MeetingMgt