apiVersion: v1
kind: Service
metadata:
  labels:
    app: UserMGTsrv
    service: UserMGTsrv
  name: UserMGTsrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: UserMGT