// List of countries with their codes
export const countries = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (Democratic Republic)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Cote d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea (North)" },
  { code: "KR", name: "Korea (South)" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" }
];

// List of country codes with their dial codes
export const countryCodes = [
  { code: "AF", dial_code: "+93", name: "Afghanistan" },
  { code: "AL", dial_code: "+355", name: "Albania" },
  { code: "DZ", dial_code: "+213", name: "Algeria" },
  { code: "AD", dial_code: "+376", name: "Andorra" },
  { code: "AO", dial_code: "+244", name: "Angola" },
  { code: "AG", dial_code: "+1-268", name: "Antigua and Barbuda" },
  { code: "AR", dial_code: "+54", name: "Argentina" },
  { code: "AM", dial_code: "+374", name: "Armenia" },
  { code: "AU", dial_code: "+61", name: "Australia" },
  { code: "AT", dial_code: "+43", name: "Austria" },
  { code: "AZ", dial_code: "+994", name: "Azerbaijan" },
  { code: "BS", dial_code: "+1-242", name: "Bahamas" },
  { code: "BH", dial_code: "+973", name: "Bahrain" },
  { code: "BD", dial_code: "+880", name: "Bangladesh" },
  { code: "BB", dial_code: "+1-246", name: "Barbados" },
  { code: "BY", dial_code: "+375", name: "Belarus" },
  { code: "BE", dial_code: "+32", name: "Belgium" },
  { code: "BZ", dial_code: "+501", name: "Belize" },
  { code: "BJ", dial_code: "+229", name: "Benin" },
  { code: "BT", dial_code: "+975", name: "Bhutan" },
  { code: "BO", dial_code: "+591", name: "Bolivia" },
  { code: "BA", dial_code: "+387", name: "Bosnia and Herzegovina" },
  { code: "BW", dial_code: "+267", name: "Botswana" },
  { code: "BR", dial_code: "+55", name: "Brazil" },
  { code: "BN", dial_code: "+673", name: "Brunei" },
  { code: "BG", dial_code: "+359", name: "Bulgaria" },
  { code: "BF", dial_code: "+226", name: "Burkina Faso" },
  { code: "BI", dial_code: "+257", name: "Burundi" },
  { code: "CV", dial_code: "+238", name: "Cabo Verde" },
  { code: "KH", dial_code: "+855", name: "Cambodia" },
  { code: "CM", dial_code: "+237", name: "Cameroon" },
  { code: "CA", dial_code: "+1", name: "Canada" },
  { code: "CF", dial_code: "+236", name: "Central African Republic" },
  { code: "TD", dial_code: "+235", name: "Chad" },
  { code: "CL", dial_code: "+56", name: "Chile" },
  { code: "CN", dial_code: "+86", name: "China" },
  { code: "CO", dial_code: "+57", name: "Colombia" },
  { code: "KM", dial_code: "+269", name: "Comoros" },
  { code: "CG", dial_code: "+242", name: "Congo" },
  { code: "CD", dial_code: "+243", name: "Congo (Democratic Republic)" },
  { code: "CR", dial_code: "+506", name: "Costa Rica" },
  { code: "CI", dial_code: "+225", name: "Cote d'Ivoire" },
  { code: "HR", dial_code: "+385", name: "Croatia" },
  { code: "CU", dial_code: "+53", name: "Cuba" },
  { code: "CY", dial_code: "+357", name: "Cyprus" },
  { code: "CZ", dial_code: "+420", name: "Czech Republic" },
  { code: "DK", dial_code: "+45", name: "Denmark" },
  { code: "DJ", dial_code: "+253", name: "Djibouti" },
  { code: "DM", dial_code: "+1-767", name: "Dominica" },
  { code: "DO", dial_code: "+1-809", name: "Dominican Republic" },
  { code: "EC", dial_code: "+593", name: "Ecuador" },
  { code: "EG", dial_code: "+20", name: "Egypt" },
  { code: "SV", dial_code: "+503", name: "El Salvador" },
  { code: "GQ", dial_code: "+240", name: "Equatorial Guinea" },
  { code: "ER", dial_code: "+291", name: "Eritrea" },
  { code: "EE", dial_code: "+372", name: "Estonia" },
  { code: "SZ", dial_code: "+268", name: "Eswatini" },
  { code: "ET", dial_code: "+251", name: "Ethiopia" },
  { code: "FJ", dial_code: "+679", name: "Fiji" },
  { code: "FI", dial_code: "+358", name: "Finland" },
  { code: "FR", dial_code: "+33", name: "France" },
  { code: "GA", dial_code: "+241", name: "Gabon" },
  { code: "GM", dial_code: "+220", name: "Gambia" },
  { code: "GE", dial_code: "+995", name: "Georgia" },
  { code: "DE", dial_code: "+49", name: "Germany" },
  { code: "GH", dial_code: "+233", name: "Ghana" },
  { code: "GR", dial_code: "+30", name: "Greece" },
  { code: "GD", dial_code: "+1-473", name: "Grenada" },
  { code: "GT", dial_code: "+502", name: "Guatemala" },
  { code: "GN", dial_code: "+224", name: "Guinea" },
  { code: "GW", dial_code: "+245", name: "Guinea-Bissau" },
  { code: "GY", dial_code: "+592", name: "Guyana" },
  { code: "HT", dial_code: "+509", name: "Haiti" },
  { code: "HN", dial_code: "+504", name: "Honduras" },
  { code: "HU", dial_code: "+36", name: "Hungary" },
  { code: "IS", dial_code: "+354", name: "Iceland" },
  { code: "IN", dial_code: "+91", name: "India" },
  { code: "ID", dial_code: "+62", name: "Indonesia" },
  { code: "IR", dial_code: "+98", name: "Iran" },
  { code: "IQ", dial_code: "+964", name: "Iraq" },
  { code: "IE", dial_code: "+353", name: "Ireland" },
  { code: "IL", dial_code: "+972", name: "Israel" },
  { code: "IT", dial_code: "+39", name: "Italy" },
  { code: "JM", dial_code: "+1-876", name: "Jamaica" },
  { code: "JP", dial_code: "+81", name: "Japan" },
  { code: "JO", dial_code: "+962", name: "Jordan" },
  { code: "KZ", dial_code: "+7", name: "Kazakhstan" },
  { code: "KE", dial_code: "+254", name: "Kenya" },
  { code: "KI", dial_code: "+686", name: "Kiribati" },
  { code: "KP", dial_code: "+850", name: "Korea (North)" },
  { code: "KR", dial_code: "+82", name: "Korea (South)" },
  { code: "KW", dial_code: "+965", name: "Kuwait" },
  { code: "KG", dial_code: "+996", name: "Kyrgyzstan" },
  { code: "LA", dial_code: "+856", name: "Laos" },
  { code: "LV", dial_code: "+371", name: "Latvia" },
  { code: "LB", dial_code: "+961", name: "Lebanon" },
  { code: "LS", dial_code: "+266", name: "Lesotho" },
  { code: "LR", dial_code: "+231", name: "Liberia" },
  { code: "LY", dial_code: "+218", name: "Libya" },
  { code: "LI", dial_code: "+423", name: "Liechtenstein" },
  { code: "LT", dial_code: "+370", name: "Lithuania" },
  { code: "LU", dial_code: "+352", name: "Luxembourg" },
  { code: "MG", dial_code: "+261", name: "Madagascar" },
  { code: "MW", dial_code: "+265", name: "Malawi" },
  { code: "MY", dial_code: "+60", name: "Malaysia" },
  { code: "MV", dial_code: "+960", name: "Maldives" },
  { code: "ML", dial_code: "+223", name: "Mali" },
  { code: "MT", dial_code: "+356", name: "Malta" },
  { code: "MH", dial_code: "+692", name: "Marshall Islands" },
  { code: "MR", dial_code: "+222", name: "Mauritania" },
  { code: "MU", dial_code: "+230", name: "Mauritius" },
  { code: "MX", dial_code: "+52", name: "Mexico" },
  { code: "FM", dial_code: "+691", name: "Micronesia" },
  { code: "MD", dial_code: "+373", name: "Moldova" },
  { code: "MC", dial_code: "+377", name: "Monaco" },
  { code: "MN", dial_code: "+976", name: "Mongolia" },
  { code: "ME", dial_code: "+382", name: "Montenegro" },
  { code: "MA", dial_code: "+212", name: "Morocco" },
  { code: "MZ", dial_code: "+258", name: "Mozambique" },
  { code: "MM", dial_code: "+95", name: "Myanmar" },
  { code: "NA", dial_code: "+264", name: "Namibia" },
  { code: "NR", dial_code: "+674", name: "Nauru" },
  { code: "NP", dial_code: "+977", name: "Nepal" },
  { code: "NL", dial_code: "+31", name: "Netherlands" },
  { code: "NZ", dial_code: "+64", name: "New Zealand" },
  { code: "NI", dial_code: "+505", name: "Nicaragua" },
  { code: "NE", dial_code: "+227", name: "Niger" },
  { code: "NG", dial_code: "+234", name: "Nigeria" },
  { code: "MK", dial_code: "+389", name: "North Macedonia" },
  { code: "NO", dial_code: "+47", name: "Norway" },
  { code: "OM", dial_code: "+968", name: "Oman" },
  { code: "PK", dial_code: "+92", name: "Pakistan" },
  { code: "PW", dial_code: "+680", name: "Palau" },
  { code: "PA", dial_code: "+507", name: "Panama" },
  { code: "PG", dial_code: "+675", name: "Papua New Guinea" },
  { code: "PY", dial_code: "+595", name: "Paraguay" },
  { code: "PE", dial_code: "+51", name: "Peru" },
  { code: "PH", dial_code: "+63", name: "Philippines" },
  { code: "PL", dial_code: "+48", name: "Poland" },
  { code: "PT", dial_code: "+351", name: "Portugal" },
  { code: "QA", dial_code: "+974", name: "Qatar" },
  { code: "RO", dial_code: "+40", name: "Romania" },
  { code: "RU", dial_code: "+7", name: "Russia" },
  { code: "RW", dial_code: "+250", name: "Rwanda" },
  { code: "KN", dial_code: "+1-869", name: "Saint Kitts and Nevis" },
  { code: "LC", dial_code: "+1-758", name: "Saint Lucia" },
  { code: "VC", dial_code: "+1-784", name: "Saint Vincent and the Grenadines" },
  { code: "WS", dial_code: "+685", name: "Samoa" },
  { code: "SM", dial_code: "+378", name: "San Marino" },
  { code: "ST", dial_code: "+239", name: "Sao Tome and Principe" },
  { code: "SA", dial_code: "+966", name: "Saudi Arabia" },
  { code: "SN", dial_code: "+221", name: "Senegal" },
  { code: "RS", dial_code: "+381", name: "Serbia" },
  { code: "SC", dial_code: "+248", name: "Seychelles" },
  { code: "SL", dial_code: "+232", name: "Sierra Leone" },
  { code: "SG", dial_code: "+65", name: "Singapore" },
  { code: "SK", dial_code: "+421", name: "Slovakia" },
  { code: "SI", dial_code: "+386", name: "Slovenia" },
  { code: "SB", dial_code: "+677", name: "Solomon Islands" },
  { code: "SO", dial_code: "+252", name: "Somalia" },
  { code: "ZA", dial_code: "+27", name: "South Africa" },
  { code: "SS", dial_code: "+211", name: "South Sudan" },
  { code: "ES", dial_code: "+34", name: "Spain" },
  { code: "LK", dial_code: "+94", name: "Sri Lanka" },
  { code: "SD", dial_code: "+249", name: "Sudan" },
  { code: "SR", dial_code: "+597", name: "Suriname" },
  { code: "SE", dial_code: "+46", name: "Sweden" },
  { code: "CH", dial_code: "+41", name: "Switzerland" },
  { code: "SY", dial_code: "+963", name: "Syria" },
  { code: "TJ", dial_code: "+992", name: "Tajikistan" },
  { code: "TZ", dial_code: "+255", name: "Tanzania" },
  { code: "TH", dial_code: "+66", name: "Thailand" },
  { code: "TL", dial_code: "+670", name: "Timor-Leste" },
  { code: "TG", dial_code: "+228", name: "Togo" },
  { code: "TO", dial_code: "+676", name: "Tonga" },
  { code: "TT", dial_code: "+1-868", name: "Trinidad and Tobago" },
  { code: "TN", dial_code: "+216", name: "Tunisia" },
  { code: "TR", dial_code: "+90", name: "Turkey" },
  { code: "TM", dial_code: "+993", name: "Turkmenistan" },
  { code: "TV", dial_code: "+688", name: "Tuvalu" },
  { code: "UG", dial_code: "+256", name: "Uganda" },
  { code: "UA", dial_code: "+380", name: "Ukraine" },
  { code: "AE", dial_code: "+971", name: "United Arab Emirates" },
  { code: "GB", dial_code: "+44", name: "United Kingdom" },
  { code: "US", dial_code: "+1", name: "United States" },
  { code: "UY", dial_code: "+598", name: "Uruguay" },
  { code: "UZ", dial_code: "+998", name: "Uzbekistan" },
  { code: "VU", dial_code: "+678", name: "Vanuatu" },
  { code: "VA", dial_code: "+379", name: "Vatican City" },
  { code: "VE", dial_code: "+58", name: "Venezuela" },
  { code: "VN", dial_code: "+84", name: "Vietnam" },
  { code: "YE", dial_code: "+967", name: "Yemen" },
  { code: "ZM", dial_code: "+260", name: "Zambia" },
  { code: "ZW", dial_code: "+263", name: "Zimbabwe" }
];